### PR TITLE
fixed for LibXL 3.8.4 and above

### PR DESCRIPTION
**Pull request by dmytroskr**

### CODE REVIEW

**Comment by zUsername** [comment]
Hi sir, @dmytroskr.
Where I can find ur fixed php_excel.dll for PHP 7.2?
Thank you.

**Comment by johmue** [comment]
Hi @zUsername,

@Jan-E is often providing latest builds with merged PRs here: https://www.apachelounge.com/viewtopic.php?t=6359

Unfortunately this repository is somehow abandoned.

**Comment by Jan-E** [comment]
Please review and merge my patches for the PHP7 branch:
https://github.com/doPhp/Excel/compare/php7...Jan-E:php7_with_pulls?expand=1

I cannot create a PR and canot open an issue, because you have limited itt:
> An owner of this repository has limited the ability to open a pull request to users that are collaborators on this repository.

**Comment by Jan-E** [comment]
Please also review and merge my patches for the PHP5 branch:
https://github.com/doPhp/Excel/compare/master...Jan-E:php5_with_pulls?expand=1

**Comment by do-io** [comment]
@Jan-E you can create PR for these. Let's PR to php5 and php7 branches

**Comment by Jan-E** [comment]
Will do when I find the time. However I do not see a compelling reason to make a distinction between the main branch and the PHP 7 branch. Let us keep them together as long as possible. Maybe a separate PHP 5 branch makes more sense.

**Pull request closed without merging**
