### PR TITLE
PHP7 compatible branch

### PR DESCRIPTION
**Pull request by johmue**
**!!! PLEASE DO NOT MERGE - PLACE IN SEPARATE BRANCH !!!**

I've created a separate PHP7 branch where I've set the requirements to:

   - LibXL >= 3.6.0.0
   - PHP >= 7.0.0

Since it can not be merged to master it needs to remain as a separate branch for now. It's tested on Win and Linux and passes all tests (at least for Win / no credentials for Lin). I'd like to replace warnings on read/write errors with exceptions but for the moment it is meant to be fully backwards compatible to existing code base.

### CODE REVIEW

**Comment by iliaal** [comment]
Johannes are there any patches you want to merge before I package the next release?

**Comment by denaje** [comment]
Looking forward to this! However it looks like there are some conflicts with master. I don't mean to be a bother, but any chance you could take a look at this?

**Comment by johmue** [comment]
I'm very sorry but I don't have the time and knowledge to rewrite the patch to be compatible with master. Since the change from VC11 to VC14 I even struggle  to compile it on my Windows machine which I use for development.

**Comment by pilif** [comment]
at least on the mac, this PR currently seems to corrupt the internal `BookHandle` somewhere between constructor and destructor. I'll do a bit of research on this and make a PR against your PR I guess :-)

**Comment by johmue** [comment]
Would be glad to receive a PR and make it work finally ...

**Comment by pilif** [comment]
IMHO, the declaration of the backing objects are in the wrong order. 

you do

```C
typedef struct _excel_book_object {
	zend_object	std;
	BookHandle book;
} excel_book_object;
```

but the function to extract the book object is using

`obj - XtOffsetOf `. 

According to [the docs](https://wiki.php.net/phpng-upgrading), the custom data should now come *before* the `zend_object` data which would explain why you need to subtract the XtOffsetOf. Let's see...

**Comment by pilif** [comment]
changing the declaration order does wonders :-)

**Comment by pilif** [comment]
ok @johmue I have submitted a PR against your PHP7 branch - fixing the declaration order fixes all tests and all segfaults go away.

**Comment by pilif** [comment]
this is definitely caused by 

```C
	if (!name_zs || name_zs->len < 1 || !key_zs || key_zs->len < 1) {
		RETURN_FALSE;
	}
```

(in my case, I'm using the version of the library built from source code, so the name/key are meaningless and set to '' in my case)

Generally, I have two issues in how the library currently handles this:

1. I don't like boolean parameters to start with, but what's even worse is that the library unconditionally creates an old-style Excel object only to throw it away and create a new-style one whenever that boolean parameter is true.

2. I don't like the mandatory arguments in the constructor for setting the license key - an explicit method would be much nicer.

Of course 2) can't be fixed without changing the API, but I should at least look into an `autoconf` test to see whether `xlBookSetKey` even exists. In the source code licensed version of the library, the symbol doesn't exist, so I have to manually patch the call out in our build or I'll crash at run time.

For 1), we probably should not be calling `xlCreateBook` in `excel_object_new_book` but instead only call it in the constructor

If you want me to, I can produce another PR that adds the autoconf check and changes the book initialization.

**Comment by iliaal** [comment]
Merged into php7 branch with some tweaks

**Pull request closed without merging**
